### ISSUE TITLE
Thortils Error

### ISSUE THREAD

**Issue by jeongeun980906** [zkytony/cos-pomdp#4]
Hello! 

I am trying to run this code, but i think it has issue on access.

Cloning into 'thortils'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.

I am not sure if this repository is public.. Would you mind checking this one?

**Comment by jeongeun980906** [comment]
https://github.com/zkytony/dinterex
https://github.com/zkytony/dmjolnir

Repository for iterex and mjolnir is not found either

**Comment by zkytony** [comment]
Hi, thanks for checking this out!

thortils is indeed public: https://github.com/zkytony/thortils 
You should be able to clone it. Did you set up SSH key of your local computer on your github account?

For the other two, I just made them public. Those are copies of the repos of two other papers, which didn't end up being involved in this project's experiments. So you can just skip them actually. I should remove those two submodules from this repo when I have a chance.

**Comment by jeongeun980906** [comment]
Thank you!

And I also found there isn't any detection on `python test_vision_detector_search.py`

**Comment by zkytony** [comment]
What do you mean by detection here? Do you mean object detection through YOLOv5? It should be set up after you follow the steps on README.
